---
- hosts: all
  roles:
    - geerlingguy.nfs
    - geerlingguy.pip
    - geerlingguy.docker

  tasks:
    - name: Create app mount path
      file:
        path: "{{ gitea_app_volume }}"
        state: directory
    - name: Create db mount path
      file:
        path: "{{ gitea_db_volume }}"
        state: directory
    - name: Mount app directory
      mount:
        path: "{{ gitea_app_volume }}"
        src: "{{ gitea_app_remote_volume }}"
        fstype: nfs
        state: mounted
    - name: Mount db directory
      mount:
        path: "{{ gitea_db_volume }}"
        src: "{{ gitea_db_remote_volume }}"
        fstype: nfs
        state: mounted
    - name: Deploy docker containers
      docker_service:
        project_name: gitea
        definition:
          version: '2'
          networks:
            gitea:
              external: false
          services:
            db:
              image: "postgres:{{ postgres_version }}"
              user: "{{ gitea_user }}:{{ gitea_group }}"
              restart: always
              environment:
                - "POSTGRES_USER={{ gitea_db_user }}"
                - "POSTGRES_PASSWORD={{ gitea_db_pass }}"
                - "POSTGRES_DB={{ gitea_db_name }}"
              networks:
                - gitea
              volumes:
                - "{{ gitea_db_volume }}:/var/lib/postgresql/data"
            app:
              image: "gitea/gitea:{{ gitea_version }}"
              environment:
                - "USER_UID={{ gitea_user }}"
                - "USER_GID={{ gitea_group }}"
                - DB_TYPE=postgres
                - DB_HOST=db:5432
                - "DB_NAME={{ gitea_db_name }}"
                - "DB_USER={{ gitea_db_user }}"
                - "DB_PASSWD={{ gitea_db_pass }}"
              restart: always
              networks:
                - gitea
              volumes:
                - "{{ gitea_app_volume }}:/data"
              ports:
                - "{{ gitea_http_port }}:3000"
                - "{{ gitea_ssh_port }}:22"
              depends_on:
                - db

    - name: Open firewall port
      firewalld:
        zone: public
        port: "{{ gitea_http_port }}/tcp"
        immediate: yes
        permanent: yes
        state: enabled

    - name: Verify DB is running
      assert:
        that:
          - "db.gitea_db_1.state.running"

    - name: Verify App is running
      assert:
        that:
          - "app.gitea_app_1.state.running"